/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module full_adder_tester_4 (
    input a,
    input b,
    input ci,
    input s,
    input co,
    output reg s_correct,
    output reg co_correct
  );
  
  
  
  wire [1-1:0] M_fa_s;
  wire [1-1:0] M_fa_co;
  reg [1-1:0] M_fa_a;
  reg [1-1:0] M_fa_b;
  reg [1-1:0] M_fa_ci;
  full_adder_processor_6 fa (
    .a(M_fa_a),
    .b(M_fa_b),
    .ci(M_fa_ci),
    .s(M_fa_s),
    .co(M_fa_co)
  );
  
  always @* begin
    M_fa_a = a;
    M_fa_b = b;
    M_fa_ci = ci;
    s_correct = ~(s ^ M_fa_s);
    co_correct = ~(co ^ M_fa_co);
  end
endmodule
